### ISSUE TITLE
basic ansible copy cannot find file

### ISSUE THREAD

**Issue by phosphene** [neillturner/kitchen-ansible#10]
The following fully qualified path copy command does not work under kitchen-ansible:

```
- name: copy app war
  copy:
    src=/tmp/rest-api-1.0.0-SNAPSHOT.war
    dest=/home/{{ user }}/devops_{{ deploy_stamp }}.war
    owner={{ user }}
    group={{ group }}
    mode=0644
  tags:
    - deploy

```

results in
```
fatal: [localhost] => input file not found at /tmp/rest-api-1.0.0-SNAPSHOT.war or /tmp/rest-api-1.0.0-SNAPSHOT.war       
```

any thoughts?

**Comment by trinitronx** [comment]
@neillturner:  Again thanks for your work on starting this great project!  I've got other things that take up my time at work also, so I understand.

That said...  I've got a bit of time at home now, and I felt I wanted to address the question since I think I see what's going on.

@phosphene:  The problem is that the files you're adding are from `/tmp` which is outside the path that `kitchen-ansible` copies _into_ the `test-kitchen` VM prior to running `ansible-playbook` _inside_ the VM.

The way that `test-kitchen`, `kitchen-ansible` and `kitchen-puppet` work is that they [first copy files into a sandbox directory][9] **inside** the VM, then [run][10] the [appropriate][11] [provisioner][12] via `Kitchen::Provisioner::MyProvisionerClassHere#run_command()` also **inside** the VM.

This differs from the workflow you're probably used to which is more akin to a "push" method rather than a `chef-solo` or `chef-client` type "pull" method.  That is to say:  You usually run Ansible on an "Ansible Host" and it makes SSH connections out to other hosts to push configuration changes out to them.  (In reality, it really doesn't matter where you run Ansible from, just as long as that host has Ansible installed on it and it can access the other hosts in your inventory.)

Test Kitchen is different.  This is because it was built around Chef.  `chef-client` usually runs on the machine you want to configure and pulls changes from your single source of truth about configuration data:  The [Chef Server][3].  [Puppet agent][5] also works similarly, pulling changes from the ["Puppet Master"][6].  With Ansible... there's no server component to act as a store of Configuration Managment code & data.  However, your [Ansible Playbook Repo][13] serves this purpose.  Ansible uses the CM code and data stored in your playbook repo to provision a host.  As mentioned before, it doesn't really matter where you run Ansible as long as it is installed, has access to playbooks & configuration data, and can contact the hosts in your [inventory][7].  Ansible can be told to run tasks on the local host using `host: localhost` + `--connection=local` or `connection: local`, or an inventory file that includes `localhost`, or the loopback address `127.0.0.1`.  You can also delegate certain tasks to the Ansible Host with [`delegate_to`][8].  Chef also has a tool that is slightly more similar to Ansible in this local mode of operation.  It's called [`chef-solo`][4].  `chef-solo` works by using a directory of CM code and data to provision a host... and it's run locally on the host that you're provisioning.

## Back to your playbook

So probably the solution for your problem is to copy files from a path relative to your role directory or playbook directory.  It's usually best practice to include static files in Ansible roles under the `files` directory, and Jinja2 templates in `templates`.  Then, in your role's `tasks/foo.yml` you would use the `copy` or `template` module to copy things from the appropriate `src` directory included with and distributed with the role.  For playbooks: it's common practice to also include a `files` directory right alongside the playbook's `.yml` file.  This way, you can distribute files that your playbook depends on alongside your playbook and ideally check them into source control if they need to be versioned.  Sharing your playbook amongst team mates is then easy and (_usually_) guaranteed to work.

One caveat however: It's generally not a good idea to [check in binary files][1] like `rest-api-1.0.0-SNAPSHOT.war` into git (or your source control of choice).  It makes your repo bloated and slow to checkout.  It also can cause problems when checking in files and checking out the repo on a machine with low memory.  So the solution to your problem is probably to store your Java EE `.war` file on a fileserver repo and use the [`get_url`][2] module to download it to a `/tmp` or `/var/cache/ansible` path inside the VM, and then use a copy from there.

I've been realizing that playbooks which expect to copy files from the "Ansible Host" system are hard to test in and of themselves just due to the way that `kitchen-ansible` currently works...  However, while I'm sure copying files this way is convenient to "just get things done"... following this pattern has the tendency to also create sticky hidden dependencies on files which live on the Ansible Host.  If you shared your playbook with someone else without these files, it would not work.  Therefore, one of the benefits of your Configuration Management system is thrown out... you can't easily reproduce & repeat the provisioning process if your Ansible Host dies & you lose those files.

[1]: https://robinwinslow.co.uk/2013/06/11/dont-ever-commit-binary-files-to-git/
[2]: http://docs.ansible.com/get_url_module.html
[3]: http://docs.chef.io/chef_server.html
[4]: https://docs.chef.io/chef_solo.html
[5]: https://docs.puppetlabs.com/references/3.4.2/man/agent.html
[6]: https://docs.puppetlabs.com/references/3.4.latest/man/master.html
[7]: http://docs.ansible.com/intro_inventory.html
[8]: http://docs.ansible.com/playbooks_delegation.html#delegation
[9]: https://github.com/neillturner/kitchen-ansible/blob/master/lib/kitchen/provisioner/ansible_playbook.rb#L265-L272
[10]: https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/provisioner/chef_solo.rb#L43-L57
[11]: https://github.com/neillturner/kitchen-puppet/blob/master/lib/kitchen/provisioner/puppet_apply.rb#L335-L357
[12]: https://github.com/neillturner/kitchen-ansible/blob/master/lib/kitchen/provisioner/ansible_playbook.rb#L310-L321
[13]: http://docs.ansible.com/playbooks_best_practices.html#content-organization

**Comment by phosphene** [comment]
thank you so much for the work. I followed your suggestions and I copied the files from the files directory.

**Comment by metmajer** [comment]
@trinitronx Great explanation! :+1:
