### ISSUE TITLE
Tasks delegated to localhost are executed on provisioned host

### ISSUE THREAD

**Issue by Lirt** [neillturner/kitchen-ansible#269]
Hello,

I found fundamental issue during testing task which is delegated to localhost. Let's say I want to execute task on my "controller" machine (task such as creating encrypted keys and safely distributing them, there are also other use cases) and then do something with it on deployed (tested) machine. 

Obviously I will use clause `delegate_to: 127.0.0.1`, but this will actually delegate task to provisioned host, because it is also created as localhost. 

Now to show you specific use case you can look at my fork of [ansible-relayor](https://github.com/Lirt/ansible-relayor/tree/feat/test-kitchen-ci) where I try to setup CI. In this case Tor keys are generated on controller machine and delivered to provisioned Tor machine, but the [delegated task](https://github.com/Lirt/ansible-relayor/blob/feat/test-kitchen-ci/tasks/main.yml#L18) fails, because it is not tested on my controller machine, but on provisioned.

Is there a way how to deal with it, or do you have any ideas how to resolve this?

Versions:
* kitchen-ansible version 0.48.1
* test-kitchen version 1.18.0

Edit:
* Using Vagrant 2.0.1 driver with VirtualBox 5.2

**Comment by lobsterdore** [comment]
I think this is a fundamental issue with this driver, it copies everything to the remote machine and executes locally Ansible from there, personally I think it would be much quicker and less fiddly to simple provision a machine remotely.

**Comment by Lirt** [comment]
There is option `ansible_connection` in [docs](https://github.com/neillturner/kitchen-ansible/blob/master/provisioner_options.md) where you can override local provisioner to SSH, but this doesn't solve the issue. 

However if driver find an option to catch IP address of provisioned machine, it can make inventory file with host for example `test-kitchen-host` and its IP address.

**Comment by trinitronx** [comment]
@Lirt:  Yes, the behavior you describe is a common confusion point with `kitchen-ansible`.  It's discussed a bit in #137 and #201.

@neillturner says it better than I can:

>  the idea is to not pollute your workstation with an ansible install and if you are running a windows station you can't install ansible on it and many corporates where I contract force you to use windows workstations.

Historically, this is partially due to the way `test-kitchen` originally worked.  The (cookbooks), playbooks, roles, etc.. are copied into the VM, then `ansible-playbook` is run from inside the VM.  This is because of course `test-kitchen` was originally for testing Chef cookbooks, and so they ran `chef-client` from inside the VM, using either local Chef repo with `chef-solo` or with minimal Chef Zero server and VM-local cookbook repo.

Now that this project has been developed as a plugin for [`test-kitchen`][kitchen-ci], and has matured a little, there are new run mode options with [`kitchen-verifier-serverspec`][1] that support running ServerSpec from your local machine (not from inside VM as usual).  As far as running `ansible-playbook` also from local machine, there are from my understanding a couple options:

1. [`kitchen-ansiblepush`][ansible-push]:  A provisioner for running ansible in normal "push" (SSH to VM) mode.  This sounds like what you want, but requires `ansible` and `ansible-playbook` commands to be installed and on your system's `$PATH`.  The [README][test-kitchen-exec-driver] has a section mentioning this.
2.  [Dynamic Inventory][ansible-inventory] via [`prepare_inventory`][prep-inventory] copy: After `kitchen-ansible` version `0.0.39`, there is support dynamic inventory scripts in the `inventory` directory.  To use this, just use dynamic inventory scripts like you would normally in a directory named `inventory`.  Ansible will run these as usual, and you can have multiple inventory files & scripts in there.
3. [Using multiple VMs in EC2][ec2-multi-vm]: @neillturner posted a great tutorial on how to set up a more complex testing infrastructure using multiple VMs in EC2.  Basically it runs Ansible from one of these, then provisions & test other VMs via ServerSpec.  Pretty neat!



[1]: https://github.com/neillturner/kitchen-verifier-serverspec
[kitchen-ci]: https://kitchen.ci/
[ansible-push]: https://github.com/ahelal/kitchen-ansiblepush
[ansible-inventory]: http://docs.ansible.com/ansible/latest/intro_dynamic_inventory.html
[test-kitchen-exec-driver]: https://github.com/neillturner/kitchen-ansible#test-kitchen-exec-driver
[prep-inventory]: https://github.com/neillturner/kitchen-ansible/blob/master/lib/kitchen/provisioner/ansible_playbook.rb#L976-L986
[ec2-multi-vm]: http://ec2dream.blogspot.com/2015/12/automated-devops-with-test-kitchen.html

**Comment by neillturner** [comment]
you can do this now using the exec driver 
see https://github.com/neillturner/ansible_exec_repo
