### ISSUE TITLE
Add support for Debian

### ISSUE THREAD

**Issue by rndmh3ro** [neillturner/kitchen-ansible#42]
Please add support for Debian 6-8.
You could either use [backports](http://backports.debian.org/Instructions/) or install Ansible directly via pip.

EDIT: You could use pip on all platforms and do not rely on package-availability of the os-maintainer. You'd only have to install pip on the target platform.

**Comment by metmajer** [comment]
Related to issue #23.

**Comment by yopeso** [comment]
compiled ansible or one installed with pip would be very cool. thanks.

**Comment by Seraf** [comment]
Hello, I'm interested too by a Debian support.

Actually I have : 
```
Fetched 4 B in 1s (3 B/s)                     
       W: Failed to fetch http://ppa.launchpad.net/ansible/ansible/ubuntu/dists/wheezy/main/source/Sources  404  Not Found
       
       W: Failed to fetch http://ppa.launchpad.net/ansible/ansible/ubuntu/dists/wheezy/main/binary-amd64/Packages  404  Not Found
       
       E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Not sure it's very relevant. The ideal way should be to install pip with distribution package, then download ansible with pip, and it will work everywhere.

**Comment by rndmh3ro** [comment]
@Seraf, this is for Ubuntu systems. Debian does not use PPAs.

The best was is to use PIP on all operating systems imo.

**Comment by neillturner** [comment]
i'll try and add a pip install option shortly

**Comment by Seraf** [comment]
@neillturner thanks, that will be a great addition and will solve one of my issue : 
I need to use private git repositories in my requirements.yml file, and it seems that ansible-galaxy with the version 1.7 is treating each line without understanding that's a yaml.
With ansible 1.9.2 my requirements file works like a charm.

**Comment by trinitronx** [comment]
@neillturner: I believe I still may have an `ansible_install.sh` script that I was using with `ansible_omnibus_url` to be able to install ansible via pip.  I think it was working on debian, ubuntu, and CentOS/RedHat, but not sure since I haven't used it in a while.  I'll see if I can find it and possibly save you some time.

**Comment by neillturner** [comment]
i was thinking of doing something simple like assuming python was installed and just doing: 
  sudo easy_install pip
  sudo pip install ansible==#{version}
and it would be up to the user to have python install on box. apparently alot of linux have this. 
but if you have a sh script i'm happy to put it in.

**Comment by Seraf** [comment]
@neillturner easy_install come with python-setuptools package which is not installed by default.
AFAIK, python-pip has the same package name on yum and apt. I guess this package should be installed to have a pip and then use it to install ansible.

What do you think ?

**Comment by rndmh3ro** [comment]
You could always install setuptools first on systems where it's not installed:
See the installation instructions here: https://pypi.python.org/pypi/setuptools#installation-instructions

Then easy_install pip, then pip install ansible.

**Comment by Seraf** [comment]
But setuptools can be already installed on the system. IMHO we should go to
the simplest solution and not install things to install things to install
things

Le mer. 26 août 2015 19:53, Sebastian Gumprich <notifications@github.com> a
écrit :

**Comment by rndmh3ro** [comment]
One can trivially check if setuptools is already installed (e.g. `which easy_install`).
But you're right, one should decide how much is assumed to be installed and how much should be tried to be installed.
You have to blance between supporting the most operating systems and thus complication the process, or assuming that e.g. the PIP-package is always called "python-pip".
IMO that's up to @neillturner to decide.

**Comment by trinitronx** [comment]
I've just posted the script I've been using with `ansible_omnibus_url` to Gist here:

https://gist.github.com/bdfd3cbb338767e58299

So far I've found some time tonight to test it against these platforms:

 - `centos-5.10` - Fails due to `pip` not working on python 2.4.. [this article provides a workaround](https://coderwall.com/p/lbr5pg/fixing-ansible-python-2-6-dependency-on-for-rhel-centos-5), but it seemed risky and wouldn't reflect most user's reality of running Ansible on CentOS 5.
 - `centos-6.4` - Works!  (Note: Has `procps` instead of `procps-ng`)
 - `centos-6.5` - Works!  (Note: Has `procps` instead of `procps-ng`)
 - `centos-7.0` - Works!  (Note: Has `procps-ng` instead of `procps`)
 - `ubuntu-10.04` - Fails due to `pycrypto` conflict
 - `ubuntu-12.04` - Works!
 - `ubuntu-14.04` - Works!
 - `ubuntu-14.10` - Works!
 - `ubuntu-15.04` - Works!
 - `debian-6.0.10` - Works!
 - `debian-7.8` - Works!
 - `debian-8.1` - Works!


At first my old version didn't work very well on Ubuntu / Debian, but after making some changes, it does!

It does some basic OS detection and tries to install all the things that Ansible needs, including some optional packages which are technically dependencies of some core Ansible modules (Ansible playbooks that use these modules would simply fail without them).  It also installs `ca-certificates` and has built-in yum failure retry ability (in my experience with RHEL / CentOS, this is important because `yum` tends to fail a lot due to stale cache and old SSL CA cert chain issues).  It also tries to install via packaged `python-pip`, and if that fails, it tries `easy_install pip`.   This ends up being a lot of things to install (mainly due to optional Ansible module dependencies), but the hope is that it covers all the bases so that some Ansible modules don't just fail unexpectedly.  The tradeoff is the amount of download / install time this takes versus a more minimal install.  I've found this useful in my own personal use to avoid having to bootstrap Ansible's dependencies using a pre-role or `pre_tasks:` in the test playbook when I just want to test one playbook or role without redoing the same work that I've already done for myself in this script.  This script was built with reliability, resiliency, and installing all "full-stack" dependencies (hence: [Omnibus](https://github.com/chef/omnibus)) in mind, not speed.

Personally I'm much more of a fan of the minimal install and speed during testing VM setup phase... and having people realize when dependencies are missing during testing their playbooks & roles is probably a good thing, because in real scenarios outside of `test-kitchen`, the plays would fail without them anyway.  However, since I need something reliable for testing my work without having to spend time fussing with various install failures or dependencies breaking my tests, I've found myself having to reach for this script when the default Ansible install in `kitchen-ansible` fails.

Perhaps some of the `yum` & `pip` reliability bits can be used to improve the way `kitchen-ansible` does the install, and the extra / optional Ansible dependencies can be kept in this "Ansible Omnibus" script since most users probably won't want to wait for all that stuff to download.  Also due to the unexpected playbook failure due to the issue of missing module dependencies outside of `test-kitchen` that I mentioned earlier.

**Comment by neillturner** [comment]
That's great. How should we implement the shell script. 
 1. We change the default location of the omnibus install to https://gist.github.com/trinitronx/bdfd3cbb338767e58299 and document it as a pip install. 
  this would be the simplest change and would make it easy to be customized?
 is there a better place to put it? in the top level of the git repo and access it via 
  https://github.com/neillturner/kitchen-ansible/ansible_install.sh
  the downside of this is when it gets changed in github i would immediately impact folks.
  So we need a way of versioning it. So maybe it is better to leave as a gist. I'm not sure how you version gists etc. or is there a better place. 
 
  2. We could make it more obvious by have a pip install option in addition to the omnibus install option. 

  3. we could move the shell script into the ruby code and pass it in to run. This would be the biggest change.

**Comment by neillturner** [comment]
If we can agree this change then i will put in it and release a new version also with your default change for busser.

**Comment by neillturner** [comment]
there is good info here 
  http://stackoverflow.com/questions/4604663/download-single-files-from-github

if i put in top level then download url would be: 
https://raw.githubusercontent.com/neillturner/kitchen-ansible/master/ansible_install.sh

and you can look at previous versions via 
https://raw.githubusercontent.com/neillturner/kitchen-ansible/2b13f3e48df206aa92626415ebd6cff3e485e0f2/ansible_install.sh
ie you use the internal commit number. 

so i think easiest way it to put your ansible_install.sh in the top level and set the 
omnimbus download url to default to https://raw.githubusercontent.com/neillturner/kitchen-ansible/master/ansible_install.sh
and document how to get to older version via commit ids. 

If that sounds good i will make changes and release.

**Comment by rndmh3ro** [comment]
Sounds definetly good to me!

**Comment by neillturner** [comment]
any comment  @trinitronx trinitronx ?

**Comment by neillturner** [comment]
I was thinking of creating a new project omnibus-ansible to contain the script and then the download location would be: 
   https://raw.githubusercontent.com/neillturner/omnibus-ansible/master/ansible_install.sh

**Comment by trinitronx** [comment]
@neillturner:  sounds good to me to keep it as either separate project or in this repo.  I'd just want to make sure we can both have ability to modify and push fixes to it.  Keeping this as a separate script just for use with `ansible_omnibus_url` is what I'd prefer.  It seems a bit over reaching to force users to install all of ansible's optional module dependencies all the time.  If we make changes to the install commands inside the ruby code, I'd think we would only want to add ansible itself, and maybe the yum/ssl fixes.  Adding a pip install option feels appropriate at some point too.

The GitHub raw link method is pretty much the way I was thinking of implementing it.  Using raw links with commit id will effectively lock the version of the script appropriately so we don't accidentally affect users until we change the link to point to a new version.

**Comment by trinitronx** [comment]
@neillturner: For future reference, Gist's are already treated as fully fledged Git repos.  Just go to the Gist page and copy the http clone url just like a GitHub repo.  This is how I was able to test, make changes, and iterate on it by committing, pushing, and then copying the new raw url to the latest script.

**Comment by neillturner** [comment]
closing. in kitchen-ansible 0.0.24. I put this in a separate project omnibus-ansible. just thought it more obvious what is was than leaving as a gist. we can update without forcing a new install of kitchen-ansible and people can go back a version by using the commit hash in the url. So no different from the gist i suppose.

**Comment by trinitronx** [comment]
@neillturner: Works great!  Thanks!

**Comment by Seraf** [comment]
Works great for me too. Thanks, it solves all my problems :D

**Comment by metmajer** [comment]
Gave it a try 2 days ago - rocks! Thanks all, this is super helpful.

**Comment by neillturner** [comment]
you should all thank @trinitronx as it was his script. i'm just the messanger. in fact i've been amazed how many contributions i've received. thanks to everyone.
