### ISSUE TITLE
require_chef_for_busser overrides require_chef_omnibus

### ISSUE THREAD

**Issue by hslee16** [neillturner/kitchen-ansible#95]
The provisioner doesn't seem to check for the presence of require_chef_omnibus option in the config

Thus setting require_chef_omnibus: false still prompts the provisioner to install the chef omnibus.

Setting require_chef_for_busser: false will disable the installation of the chef omnibus. This should be documented in the README

**Comment by neillturner** [comment]
the code doesn't use the variable 'require_chef_omnibus'  it is only used by the chef provisioner built in to test -kitchen. 
Maybe it would have been better to use 'require_chef_omnibus' instead of 'require_chef_for_busser'. 
When you write software you name stuff at the time and well later you think it would be better to name it something else. 
I could add the parameter  'require_chef_omnibus'  as a synonym of 'require_chef_omnibus'  but i think that will just add complexity. 
If folks are confused by the parameter name hopefully they will google and find this issue and use the correct parameter name. 
closing.
